service: message

frameworkVersion: '2'

provider:
  name: fun
  handler: jobless_handler.handler
  runtime: nodejs14
plugins:
  - "@dustlight/serverless-fun"
  - "@dustlight/serverless-fun-offline"

package:
  exclude:
    - package-lock.json